# yaml-language-server: $schema=https://unpkg.com/@sveltia/cms/schema/sveltia-cms.json

backend:
  name: github
  repo: charitygamble/portfolioSite

media_folder: /public/assets/images
public_folder: /assets/images

collections:
  - name: post
    label: Posts
    label_singular: Post
    folder: src/blog
    fields:
      - { label: Layout, name: layout, widget: hidden, default: layouts/post.njk }
      - { label: Tags, name: tags, widget: list, default: ['post'] }
      - { label: Title, name: title, widget: string }
      - { label: Date, name: date, widget: datetime, type: date }
      - { label: Body, name: body, widget: richtext }